version: '3'

services:
  ingresse-backend:
    build: ./../..
    image: ingresse-backend
    container_name: ingresse-backend
    environment:
    - "GOENV=docker"
    ports:
      - "5000:5000"
    links:
      - mongodb

  ingresse-docs:
    build: ./../../docs
    image: ingresse-docs
    container_name: ingresse-docs
    ports:
    - "8000:80"
  
  mongodb:
    image: mongo:3.4
    container_name: "mongodb-ingresse"
    volumes:
      - ./data:/data/db
    restart: always
    expose:
      - 27017